<?php

namespace App\Http\Controllers;

class DeploymentController {
    //* Github CI/CD:
    // 1. Run tests on pushes.
    // 2. Run tests on pull requestDeploy when pushes are made to specific branches.
    // 3. Deploy to stagging server when push is on staging branch.
    // 4. Deploy to production server when push is on master branchDeploy when a release is tagged.
    // Workflow: A workflow defines the steps required to complete a CI/CD process.
    // Workflows are custom automated processes that you can set up in your repository to build, test, package, release, or deploy any project on Github.
    // A workflow is defined within the repository and committed as part of the repository.
    // Workflows are written with YAML and stored inside .github/workflows directory of your project root.
    // Let's say we have a PR workflow for pull request, whenever pull request happen on master or stagging server, we run tests.
    // We can define another workflow to ensure no part of the project is broken because of any change. Let's call it PUSH workflow- push_workflow.yml
    
    // For deploying: Log into your server and generate a ssh key using this command- ssh-keygen.
    // Or, if already generated, just take that key.
    // Two files named id_rsa.pub and id_rsa will be generated for you in the ~/.ssh directory.
    // copy the content of id_rsa, not id_rsa.pub. id_rsa.pub contains your public key while id_rsa contains your private key.
    // cat ~/.ssh/id_rsa
    // You need to add the public key generated by SSH keygen to the authorized_keys so that any connection attempted using the private key will be allowed.
    // cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
    // The command above will produce no output so do not worry if nothing happens after running the command.
    // Then go to github->settings->Click on 'Secrets'.
    // You need to give a name to the secret that corresponds to what has been defined in the Workflow i.e SSH_PRIVATE_KEY and then put the content you copied as the value.
    // Obtain the SSH Known Hosts of the server, from local machine run: ssh-keyscan rsa -t {server_ip_address}
    // Replace {server_ip_address} with your server public IP address.
    // Copy the output of this command and add it to the secrets with the name SSH_KNOWN_HOSTSand the content will be copied.
    // The part to copy begins with {server_ip_address} sh-rsa
    // So we added in github setiings's secrets two things server's ssh private key and local machine's hosts.
    // Add DOT_ENV_PRODUCTION and DOT_ENV_STAGING in same location of github.
    // To initialize deployment, we can use Deployer. It is a deployment tool written in PHP with support for popular frameworks out of the box.
    // composer require deployer/deployer deployer/recipes.
    // The package deployer/deployer is the main Deployer project while deployer/recipes includes components that will help us configure Deployer for specific projects and tools like Laravel, Symfony, RSync, and others.
    // Next, configure Deployer, we will do this by creating a file named deploy.php at the root of the project the code for configuration.
    // Once this file has been created with the content above, commit changes, and then push the changes to the master branch on GitHub. 
    // Go to GitHub and proceed to your project, you can click on the Actions tab to monitor the running actions, and once you do click on it, you will see that your push has triggered the workflow and the process has started already.

    // Laravel Forge is a server management tool. It doesn't host your site itself but connects to providers like DigitalOcean, AWS, or Linode to set them up for you.
    // f you are building a massive application, Laravel Vapor is a serverless deployment platform built on AWS Lambda.
    // Laravel Cloud is the most streamlined option. It is a fully managed platform where you don't even see the server.

    // We can automate test for accessibility.
    // Can automate running unit tests or frontend tests.
    // We can setup lighthouse CI with github actions integration.
    // Can automate SEO testing or can observe SEO using lighthouse integration.
    // Can automate security testing, continuous benchmarking for performance.
 }